In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
tf.__version__

'2.4.1'

In [41]:
!cd "/content/drive/MyDrive/Colab Notebooks/trash_testing/data"

In [42]:
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/trash_testing/data/Churn_Modelling.csv")

In [43]:
data.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [44]:
X = data.iloc[:, 3:-1].values
y = data.iloc[:, -1].values

In [47]:
# Filling the missing values in the dataFrame using sklearn.impute SimpleImputer method
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = "mean")
imputer.fit(X[:, 3:])

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=0)

In [48]:
X[:, 3:] = imputer.transform(X[:, 3:])
print(X)

[[619 'France' 'Female' ... 1.0 1.0 101348.88]
 [608 'Spain' 'Female' ... 0.0 1.0 112542.58]
 [502 'France' 'Female' ... 1.0 0.0 113931.57]
 ...
 [709 'France' 'Female' ... 0.0 1.0 42085.58]
 [772 'Germany' 'Male' ... 1.0 0.0 92888.52]
 [792 'France' 'Female' ... 1.0 0.0 38190.78]]


In [50]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
X[:, 2] = encoder.fit_transform(X[:, 2])

In [51]:
X   # Female - 0 
    # Male   - 1

array([[619, 'France', 0, ..., 1.0, 1.0, 101348.88],
       [608, 'Spain', 0, ..., 0.0, 1.0, 112542.58],
       [502, 'France', 0, ..., 1.0, 0.0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0.0, 1.0, 42085.58],
       [772, 'Germany', 1, ..., 1.0, 0.0, 92888.52],
       [792, 'France', 0, ..., 1.0, 0.0, 38190.78]], dtype=object)

In [52]:
# Encoding the categorical data Geo Data column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder="passthrough")
X = np.array(ct.fit_transform(X))

In [53]:
X

array([[1.0, 0.0, 0.0, ..., 1.0, 1.0, 101348.88],
       [0.0, 0.0, 1.0, ..., 0.0, 1.0, 112542.58],
       [1.0, 0.0, 0.0, ..., 1.0, 0.0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0.0, 1.0, 42085.58],
       [0.0, 1.0, 0.0, ..., 1.0, 0.0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1.0, 0.0, 38190.78]], dtype=object)

In [54]:
# split to train and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42, stratify = y, shuffle=True)

In [71]:
print("The percentage of 0 class in train data: {}%".format(round(len([x for x in y_train if x == 0]) / len(y_train) * 100), 2))

print("The percentage of  0 class in test data: {}%".format(round(len([x for x in y_test if x == 0]) / len(y_test)* 100), 2))

The percentage of 0 class in train data: 80%
The percentage of  0 class in test data: 80%


In [72]:
print("The percentage of 1 class in train data: {}%".format(round(len([x for x in y_train if x == 1]) / len(y_train) * 100), 2))

print("The percentage of  1 class in test data: {}%".format(round(len([x for x in y_test if x == 1]) / len(y_test)* 100), 2))

The percentage of 1 class in train data: 20%
The percentage of  1 class in test data: 20%


In [73]:
# Feature Scaling in order to normalize  / scale the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [75]:
# Building the Simple Neural Network
model = tf.keras.models.Sequential()

# Add the input layer and hidden layer
model.add(tf.keras.layers.Dense(units=6, activation="relu")) # input layer
model.add(tf.keras.layers.Dense(units=6, activation="relu")) # second layer
model.add(tf.keras.layers.Dense(units=1, activation="sigmoid")) # the output layer

In [77]:
model.compile(optimizer="adam", loss='binary_crossentropy', metrics=['accuracy'])

In [79]:
model.fit(X_train, y_train, batch_size=25, epochs=25, workers=-1, use_multiprocessing=True)

Epoch 1/25
320/320 [==============================] - 1s 1ms/step - loss: 0.5764 - accuracy: 0.7593
Epoch 2/25
320/320 [==============================] - 0s 1ms/step - loss: 0.4475 - accuracy: 0.8004
Epoch 3/25
320/320 [==============================] - 0s 1ms/step - loss: 0.4413 - accuracy: 0.8022
Epoch 4/25
320/320 [==============================] - 0s 1ms/step - loss: 0.4182 - accuracy: 0.8307
Epoch 5/25
320/320 [==============================] - 0s 1ms/step - loss: 0.4244 - accuracy: 0.8240
Epoch 6/25
320/320 [==============================] - 0s 1ms/step - loss: 0.4141 - accuracy: 0.8290
Epoch 7/25
320/320 [==============================] - 0s 1ms/step - loss: 0.4254 - accuracy: 0.8209
Epoch 8/25
320/320 [==============================] - 0s 1ms/step - loss: 0.3997 - accuracy: 0.8327
Epoch 9/25
320/320 [==============================] - 0s 1ms/step - loss: 0.4160 - accuracy: 0.8302
Epoch 10/25
320/320 [==============================] - 0s 1ms/step - loss: 0.3940 - accuracy: 0.8361

In [80]:
model.predict(scaler.fit_transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) # the predicted probability of churn

array([[0.05444023]], dtype=float32)

In [81]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.51)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [1 1]
 [0 0]
 [0 0]]


In [83]:
from sklearn.metrics import confusion_matrix, accuracy_score
matrix = confusion_matrix(y_test, y_pred)
print(matrix)
accuracy_score(y_test, y_pred)

[[1550   43]
 [ 243  164]]


0.857